<marquee id="gallery" class="marquee" behavior="alternative"  onmouseover="this.stop();" onmouseout="this.start();">
	 <img src="http://cssdeck.com/uploads/media/items/0/00kih8g.jpg" />
	 <img src="http://farm9.staticflickr.com/8504/8365873811_d32571df3d_z.jpg" />
	<img src="http://farm9.staticflickr.com/8061/8237246833_54d8fa37f0_z.jpg" />
	 <img src="http://farm9.staticflickr.com/8195/8098750703_797e102da2_z.jpg" />
</marquee>