<div class="w3-content" style="max-width:1200px" data-mage-init='{"slider":"slider"}'>
  <img class="mySlides" src="https://www.w3schools.com/howto/img_snow_wide.jpg" style="width:100%;display:none">
  <img class="mySlides" src="https://www.w3schools.com/howto/img_nature_wide.jpg" style="width:100%">
  <img class="mySlides" src="https://www.w3schools.com/howto/img_mountains_wide.jpg" style="width:100%;display:none">
  <img class="mySlides" src="https://www.w3schools.com/howto/img_mountains_wide.jpg" style="width:100%;display:none">

  <div class="w3-row-padding w3-section" style="display: flex;">
    <div class="w3-col s3">
      <img class="demo w3-opacity w3-hover-opacity-off" src="https://www.w3schools.com/howto/img_snow_wide.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(1)">
    </div>
    <div class="w3-col s3">
      <img class="demo w3-opacity w3-hover-opacity-off" src="https://www.w3schools.com/howto/img_nature_wide.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(2)">
    </div>
    <div class="w3-col s3">
      <img class="demo w3-opacity w3-hover-opacity-off" src="https://www.w3schools.com/howto/img_mountains_wide.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(3)">
    </div>
    <div class="w3-col s3">
      <img class="demo w3-opacity w3-hover-opacity-off" src="https://www.w3schools.com/howto/img_mountains_wide.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(3)">
    </div>
  </div>
</div>
